const countries = [
  { "id": "AF", "label": "Afghanistan", "code": "93" },
  { "id": "AL", "label": "Albania", "code": "355" },
  { "id": "DZ", "label": "Algeria", "code": "213" },
  { "id": "AS", "label": "American Samoa", "code": "1684" },
  { "id": "AD", "label": "Andorra", "code": "376" },
  { "id": "AO", "label": "Angola", "code": "244" },
  { "id": "AI", "label": "Anguilla", "code": "1264" },
  { "id": "AQ", "label": "Antarctica", "code": "672" },
  { "id": "AG", "label": "Antigua and Barbuda", "code": "1268" },
  { "id": "AR", "label": "Argentina", "code": "54" },
  { "id": "AM", "label": "Armenia", "code": "374" },
  { "id": "AW", "label": "Aruba", "code": "297" },
  { "id": "AU", "label": "Australia", "code": "61" },
  { "id": "AT", "label": "Austria", "code": "43" },
  { "id": "AZ", "label": "Azerbaijan", "code": "994" },
  { "id": "BS", "label": "Bahamas", "code": "1242" },
  { "id": "BH", "label": "Bahrain", "code": "973" },
  { "id": "BD", "label": "Bangladesh", "code": "880" },
  { "id": "BB", "label": "Barbados", "code": "1246" },
  { "id": "BY", "label": "Belarus", "code": "375" },
  { "id": "BE", "label": "Belgium", "code": "32" },
  { "id": "BZ", "label": "Belize", "code": "501" },
  { "id": "BJ", "label": "Benin", "code": "229" },
  { "id": "BM", "label": "Bermuda", "code": "1441" },
  { "id": "BT", "label": "Bhutan", "code": "975" },
  { "id": "BO", "label": "Bolivia (Plurinational State of)", "code": "591" },
  { "id": "BQ", "label": "Bonaire, Sint Eustatius and Saba", "code": "599" },
  { "id": "BA", "label": "Bosnia and Herzegovina", "code": "387" },
  { "id": "BW", "label": "Botswana", "code": "267" },
  { "id": "BV", "label": "Bouvet Island", "code": "47" },
  { "id": "BR", "label": "Brazil", "code": "55" },
  { "id": "IO", "label": "British Indian Ocean Territory", "code": "246" },
  { "id": "BN", "label": "Brunei Darussalam", "code": "673" },
  { "id": "BG", "label": "Bulgaria", "code": "359" },
  { "id": "BF", "label": "Burkina Faso", "code": "226" },
  { "id": "BI", "label": "Burundi", "code": "257" },
  { "id": "CV", "label": "Cabo Verde", "code": "238" },
  { "id": "KH", "label": "Cambodia", "code": "855" },
  { "id": "CM", "label": "Cameroon", "code": "237" },
  { "id": "CA", "label": "Canada", "code": "1" },
  { "id": "KY", "label": "Cayman Islands", "code": "1345" },
  { "id": "CF", "label": "Central African Republic", "code": "236" },
  { "id": "TD", "label": "Chad", "code": "235" },
  { "id": "CL", "label": "Chile", "code": "56" },
  { "id": "CN", "label": "China", "code": "86" },
  { "id": "CX", "label": "Christmas Island", "code": "61" },
  { "id": "CC", "label": "Cocos (Keeling) Islands", "code": "61" },
  { "id": "CO", "label": "Colombia", "code": "57" },
  { "id": "KM", "label": "Comoros", "code": "269" },
  { "id": "CG", "label": "Congo", "code": "242" },
  { "id": "CD", "label": "Congo (Democratic Republic of the)", "code": "243" },
  { "id": "CK", "label": "Cook Islands", "code": "682" },
  { "id": "CR", "label": "Costa Rica", "code": "506" },
  { "id": "HR", "label": "Croatia", "code": "385" },
  { "id": "CU", "label": "Cuba", "code": "53" },
  { "id": "CW", "label": "Curaçao", "code": "599" },
  { "id": "CY", "label": "Cyprus", "code": "357" },
  { "id": "CZ", "label": "Czech Republic", "code": "420" },
  { "id": "CI", "label": "Côte d'Ivoire", "code": "225" },
  { "id": "DK", "label": "Denmark", "code": "45" },
  { "id": "DJ", "label": "Djibouti", "code": "253" },
  { "id": "DM", "label": "Dominica", "code": "1767" },
  { "id": "DO", "label": "Dominican Republic", "code": "1" },
  { "id": "EC", "label": "Ecuador", "code": "593" },
  { "id": "EG", "label": "Egypt", "code": "20" },
  { "id": "SV", "label": "El Salvador", "code": "503" },
  { "id": "GQ", "label": "Equatorial Guinea", "code": "240" },
  { "id": "ER", "label": "Eritrea", "code": "291" },
  { "id": "EE", "label": "Estonia", "code": "372" },
  { "id": "ET", "label": "Ethiopia", "code": "251" },
  { "id": "FK", "label": "Falkland Islands (Malvinas)", "code": "500" },
  { "id": "FO", "label": "Faroe Islands", "code": "298" },
  { "id": "FJ", "label": "Fiji", "code": "679" },
  { "id": "FI", "label": "Finland", "code": "358" },
  { "id": "FR", "label": "France", "code": "33" },
  { "id": "GF", "label": "French Guiana", "code": "594" },
  { "id": "PF", "label": "French Polynesia", "code": "689" },
  { "id": "TF", "label": "French Southern Territories", "code": "262" },
  { "id": "GA", "label": "Gabon", "code": "241" },
  { "id": "GM", "label": "Gambia", "code": "220" },
  { "id": "GE", "label": "Georgia", "code": "995" },
  { "id": "DE", "label": "Germany", "code": "49" },
  { "id": "GH", "label": "Ghana", "code": "233" },
  { "id": "GI", "label": "Gibraltar", "code": "350" },
  { "id": "GR", "label": "Greece", "code": "30" },
  { "id": "GL", "label": "Greenland", "code": "299" },
  { "id": "GD", "label": "Grenada", "code": "1473" },
  { "id": "GP", "label": "Guadeloupe", "code": "590" },
  { "id": "GU", "label": "Guam", "code": "1671" },
  { "id": "GT", "label": "Guatemala", "code": "502" },
  { "id": "GG", "label": "Guernsey", "code": "44" },
  { "id": "GN", "label": "Guinea", "code": "224" },
  { "id": "GW", "label": "Guinea-Bissau", "code": "245" },
  { "id": "GY", "label": "Guyana", "code": "592" },
  { "id": "HT", "label": "Haiti", "code": "509" },
  { "id": "HM", "label": "Heard Island and McDonald Islands", "code": "672" },
  { "id": "VA", "label": "Holy See", "code": "379" },
  { "id": "HN", "label": "Honduras", "code": "504" },
  { "id": "HK", "label": "Hong Kong", "code": "852" },
  { "id": "HU", "label": "Hungary", "code": "36" },
  { "id": "IS", "label": "Iceland", "code": "354" },
  { "id": "IN", "label": "India", "code": "91" },
  { "id": "ID", "label": "Indonesia", "code": "62" },
  { "id": "IR", "label": "Iran (Islamic Republic of)", "code": "98" },
  { "id": "IQ", "label": "Iraq", "code": "964" },
  { "id": "IE", "label": "Ireland", "code": "353" },
  { "id": "IM", "label": "Isle of Man", "code": "44" },
  { "id": "IL", "label": "Israel", "code": "972" },
  { "id": "IT", "label": "Italy", "code": "39" },
  { "id": "JM", "label": "Jamaica", "code": "1876" },
  { "id": "JP", "label": "Japan", "code": "81" },
  { "id": "JE", "label": "Jersey", "code": "44" },
  { "id": "JO", "label": "Jordan", "code": "962" },
  { "id": "KZ", "label": "Kazakhstan", "code": "7" },
  { "id": "KE", "label": "Kenya", "code": "254" },
  { "id": "KI", "label": "Kiribati", "code": "686" },
  { "id": "KW", "label": "Kuwait", "code": "965" },
  { "id": "KG", "label": "Kyrgyzstan", "code": "996" },
  { "id": "LA", "label": "Lao People's Democratic Republic", "code": "856" },
  { "id": "LV", "label": "Latvia", "code": "371" },
  { "id": "LB", "label": "Lebanon", "code": "961" },
  { "id": "LS", "label": "Lesotho", "code": "266" },
  { "id": "LR", "label": "Liberia", "code": "231" },
  { "id": "LY", "label": "Libya", "code": "218" },
  { "id": "LI", "label": "Liechtenstein", "code": "423" },
  { "id": "LT", "label": "Lithuania", "code": "370" },
  { "id": "LU", "label": "Luxembourg", "code": "352" },
  { "id": "MO", "label": "Macao", "code": "853" },
  { "id": "MK", "label": "Macedonia (the former Yugoslav Republic of)", "code": "389" },
  { "id": "MG", "label": "Madagascar", "code": "261" },
  { "id": "MW", "label": "Malawi", "code": "265" },
  { "id": "MY", "label": "Malaysia", "code": "60" },
  { "id": "MV", "label": "Maldives", "code": "960" },
  { "id": "ML", "label": "Mali", "code": "223" },
  { "id": "MT", "label": "Malta", "code": "356" },
  { "id": "MH", "label": "Marshall Islands", "code": "692" },
  { "id": "MQ", "label": "Martinique", "code": "596" },
  { "id": "MR", "label": "Mauritania", "code": "222" },
  { "id": "MU", "label": "Mauritius", "code": "230" },
  { "id": "YT", "label": "Mayotte", "code": "262" },
  { "id": "MX", "label": "Mexico", "code": "52" },
  { "id": "FM", "label": "Micronesia (Federated States of)", "code": "691" },
  { "id": "MD", "label": "Moldova (Republic of)", "code": "373" },
  { "id": "MC", "label": "Monaco", "code": "377" },
  { "id": "MN", "label": "Mongolia", "code": "976" },
  { "id": "ME", "label": "Montenegro", "code": "382" },
  { "id": "MS", "label": "Montserrat", "code": "1664" },
  { "id": "MA", "label": "Morocco", "code": "212" },
  { "id": "MZ", "label": "Mozambique", "code": "258" },
  { "id": "MM", "label": "Myanmar", "code": "95" },
  { "id": "NA", "label": "Namibia", "code": "264" },
  { "id": "NR", "label": "Nauru", "code": "674" },
  { "id": "NP", "label": "Nepal", "code": "977" },
  { "id": "NL", "label": "Netherlands", "code": "31" },
  { "id": "NC", "label": "New Caledonia", "code": "687" },
  { "id": "NZ", "label": "New Zealand", "code": "64" },
  { "id": "NI", "label": "Nicaragua", "code": "505" },
  { "id": "NE", "label": "Niger", "code": "227" },
  { "id": "NG", "label": "Nigeria", "code": "234" },
  { "id": "NU", "label": "Niue", "code": "683" },
  { "id": "NF", "label": "Norfolk Island", "code": "672" },
  { "id": "KP", "label": "North Korea", "code": "850" },
  { "id": "MP", "label": "Northern Mariana Islands", "code": "1670" },
  { "id": "NO", "label": "Norway", "code": "47" },
  { "id": "OM", "label": "Oman", "code": "968" },
  { "id": "PK", "label": "Pakistan", "code": "92" },
  { "id": "PW", "label": "Palau", "code": "680" },
  { "id": "PS", "label": "Palestine, State of", "code": "970" },
  { "id": "PA", "label": "Panama", "code": "507" },
  { "id": "PG", "label": "Papua New Guinea", "code": "675" },
  { "id": "PY", "label": "Paraguay", "code": "595" },
  { "id": "PE", "label": "Peru", "code": "51" },
  { "id": "PH", "label": "Philippines", "code": "63" },
  { "id": "PN", "label": "Pitcairn", "code": "64" },
  { "id": "PL", "label": "Poland", "code": "48" },
  { "id": "PT", "label": "Portugal", "code": "351" },
  { "id": "PR", "label": "Puerto Rico", "code": "1" },
  { "id": "QA", "label": "Qatar", "code": "974" },
  { "id": "XK", "label": "Republic of Kosovo", "code": "383" },
  { "id": "RE", "label": "Réunion", "code": "262" },
  { "id": "RO", "label": "Romania", "code": "40" },
  { "id": "RU", "label": "Russian Federation", "code": "7" },
  { "id": "RW", "label": "Rwanda", "code": "250" },
  { "id": "BL", "label": "Saint Barthélemy", "code": "590" },
  { "id": "SH", "label": "Saint Helena, Ascension and Tristan da Cunha", "code": "290" },
  { "id": "KN", "label": "Saint Kitts and Nevis", "code": "1869" },
  { "id": "LC", "label": "Saint Lucia", "code": "1758" },
  { "id": "MF", "label": "Saint Martin (French part)", "code": "590" },
  { "id": "PM", "label": "Saint Pierre and Miquelon", "code": "508" },
  { "id": "VC", "label": "Saint Vincent and the Grenadines", "code": "1784" },
  { "id": "WS", "label": "Samoa", "code": "685" },
  { "id": "SM", "label": "San Marino", "code": "378" },
  { "id": "ST", "label": "Sao Tome and Principe", "code": "239" },
  { "id": "SA", "label": "Saudi Arabia", "code": "966" },
  { "id": "SN", "label": "Senegal", "code": "221" },
  { "id": "RS", "label": "Serbia", "code": "381" },
  { "id": "SC", "label": "Seychelles", "code": "248" },
  { "id": "SL", "label": "Sierra Leone", "code": "232" },
  { "id": "SG", "label": "Singapore", "code": "65" },
  { "id": "SX", "label": "Sint Maarten (Dutch part)", "code": "1721" },
  { "id": "SK", "label": "Slovakia", "code": "421" },
  { "id": "SI", "label": "Slovenia", "code": "386" },
  { "id": "SB", "label": "Solomon Islands", "code": "677" },
  { "id": "SO", "label": "Somalia", "code": "252" },
  { "id": "ZA", "label": "South Africa", "code": "27" },
  { "id": "GS", "label": "South Georgia and the South Sandwich Islands", "code": "500" },
  { "id": "KR", "label": "South Korea", "code": "82" },
  { "id": "SS", "label": "South Sudan", "code": "211" },
  { "id": "ES", "label": "Spain", "code": "34" },
  { "id": "LK", "label": "Sri Lanka", "code": "94" },
  { "id": "SD", "label": "Sudan", "code": "249" },
  { "id": "SR", "label": "Suriname", "code": "597" },
  { "id": "SJ", "label": "Svalbard and Jan Mayen", "code": "47" },
  { "id": "SZ", "label": "Swaziland", "code": "268" },
  { "id": "SE", "label": "Sweden", "code": "46" },
  { "id": "CH", "label": "Switzerland", "code": "41" },
  { "id": "SY", "label": "Syrian Arab Republic", "code": "963" },
  { "id": "TW", "label": "Taiwan", "code": "886" },
  { "id": "TJ", "label": "Tajikistan", "code": "992" },
  { "id": "TZ", "label": "Tanzania, United Republic of", "code": "255" },
  { "id": "TH", "label": "Thailand", "code": "66" },
  { "id": "TL", "label": "Timor-Leste", "code": "670" },
  { "id": "TG", "label": "Togo", "code": "228" },
  { "id": "TK", "label": "Tokelau", "code": "690" },
  { "id": "TO", "label": "Tonga", "code": "676" },
  { "id": "TT", "label": "Trinidad and Tobago", "code": "1868" },
  { "id": "TN", "label": "Tunisia", "code": "216" },
  { "id": "TR", "label": "Turkey", "code": "90" },
  { "id": "TM", "label": "Turkmenistan", "code": "993" },
  { "id": "TC", "label": "Turks and Caicos Islands", "code": "1649" },
  { "id": "TV", "label": "Tuvalu", "code": "688" },
  { "id": "UG", "label": "Uganda", "code": "256" },
  { "id": "UA", "label": "Ukraine", "code": "380" },
  { "id": "AE", "label": "United Arab Emirates", "code": "971" },
  { "id": "GB", "label": "United Kingdom", "code": "44" },
  { "id": "US", "label": "United States", "code": "1" },
  { "id": "UM", "label": "United States Minor Outlying Islands", "code": "1" },
  { "id": "UY", "label": "Uruguay", "code": "598" },
  { "id": "UZ", "label": "Uzbekistan", "code": "998" },
  { "id": "VU", "label": "Vanuatu", "code": "678" },
  { "id": "VE", "label": "Venezuela (Bolivarian Republic of)", "code": "58" },
  { "id": "VN", "label": "Viet Nam", "code": "84" },
  { "id": "VG", "label": "Virgin Islands (British)", "code": "1284" },
  { "id": "VI", "label": "Virgin Islands (U.S.)", "code": "1" },
  { "id": "WF", "label": "Wallis and Futuna", "code": "681" },
  { "id": "EH", "label": "Western Sahara", "code": "212" },
  { "id": "YE", "label": "Yemen", "code": "967" },
  { "id": "ZM", "label": "Zambia", "code": "260" },
  { "id": "ZW", "label": "Zimbabwe", "code": "263" }
]


module.exports = countries;
